route:
  group_by: ['alertname', 'datos', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h # Te volverá a avisar cada 1 hora si no lo arreglas
  receiver: 'grupo-telegram-ti'

receivers:
  - name: 'grupo-telegram-ti'
    telegram_configs:
      - bot_token: ""  # Tu token Aqui
        chat_id:       # Tu id de chat Aqui
        parse_mode: 'HTML'
        message: |-
          {{ range .Alerts }}
          {{ if eq .Status "firing" }}🔴 <b>FALLA ACTIVA</b>{{ else }}🟢 <b>RECUPERADO</b>{{ end }}
          <b>Alerta:</b> {{ .Labels.alertname }}
          <b>Equipo:</b> {{ if .Labels.datos }}{{ .Labels.datos }}{{ else }}{{ .Labels.instance }}{{ end }}
          <b>Detalle:</b> {{ .Annotations.description }}
          ---
          {{ end }}
