{
 "title": "Metricas Servidores portillosur",
 "description": "Servidores de portillosur, dashboard para ver el funcionamiento del servidor.",
 "tags": [
  "Metricas",
  "Windows",
  "Linux",
  "Main",
  "Servidores"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Seleccione un servidor",
    "query": {
     "query": "label_values(up{job=\"resources_data\"},datos)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resumen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{servidor=\"$instance\"}",
     "legendFormat": "Estado del servidor"
    }
   ]
  },
  {
   "title": "Tiempo de Actividad",
   "type": "stat",
   "description": "Indica el tiempo continuo que el servidor ha estado encendido sin reiniciarse. Permite verificar la estabilidad del sistema y confirmar si se han aplicado actualizaciones recientes que requieren reinicio.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - windows_system_boot_time_timestamp{datos=\"$instance\"}) \r\nor \r\n(time() - node_boot_time_seconds{datos=\"$instance\"})",
     "legendFormat": "Tiempo de Actividad"
    }
   ]
  },
  {
   "title": "Latencia Actual (Ping ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_icmp_duration_seconds{servidor=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Perdida de paquetes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( 1 - avg_over_time(probe_success{servidor=\"$instance\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ancho de Banda Actual",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:network_receive_bps:rate5m{datos=~\"$instance\"}) + sum(instance:network_transmit_bps:rate5m{datos=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso del CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:cpu_usage:percent{datos=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 - 100 * (windows_memory_available_bytes{datos=\"$instance\"} / windows_memory_physical_total_bytes{datos=\"$instance\"} )) \r\nor \r\n(100 - 100 * (node_memory_MemAvailable_bytes{datos=\"$instance\"} / node_memory_MemTotal_bytes{datos=\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso Disco Duro ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:disk_root_usage:percent{datos=\"$instance\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  { "title": "Inventario de Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Hostname",
   "type": "stat",
   "description": "Muestra el nombre de red asignado a esta máquina. Facilita la identificación rápida del servidor dentro de la infraestructura tecnológica de la empresa para evitar confusiones al monitorear.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:info:hostname{datos=\"$instance\"}",
     "legendFormat": "{{sys_name}}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "description": "El nombre comercial del sistema. Ayuda a identificar rápidamente el entorno y saber qué tipo de herramientas o licencias soporta.",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:info:os{datos=\"$instance\"}",
     "legendFormat": "{{sys_os}}"
    }
   ]
  },
  {
   "title": "Kernel version",
   "type": "stat",
   "description": "Es el número de actualización de la computadora. Nos sirve para saber si la máquina está al día con sus vacunas de seguridad o si está usando un sistema viejo y necesita actualizarse.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:info:kernel{datos=\"$instance\"}",
     "legendFormat": "{{sys_kernel}}"
    }
   ]
  },
  {
   "title": "Núcleos",
   "type": "stat",
   "description": "Refleja la cantidad de núcleos o procesadores lógicos disponibles. Indica la capacidad de procesamiento simultáneo del equipo, lo que define cuánta carga de trabajo pesada puede soportar sin perder rendimiento.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:cpu_cores:count{datos=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Es la cantidad total de memoria física (RAM) instalada en el servidor. Representa el límite de aplicaciones, bases de datos o procesos que la máquina puede mantener activos al mismo tiempo con un rendimiento óptimo.",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:ram_total:bytes{datos=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root mount size (Disco C: Total)",
   "type": "stat",
   "description": "Indica la capacidad máxima de almacenamiento del disco principal del sistema. Es vital para conocer el límite total de datos, programas y archivos que se pueden alojar antes de requerir una ampliación o limpieza de espacio.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:root_mount_size:bytes{datos=\"$instance\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  { "title": "Área de procesamiento", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "⚙️[Procesos Activos]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:active_processes:count{datos=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso del CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:cpu_usage:percent{datos=\"$instance\"}",
     "legendFormat": "Uso CPU"
    }
   ]
  },
  {
   "title": "Saturación (Cola del CPU)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "instance:processor_queue:length{datos=~\"$instance\"}",
     "legendFormat": "Tareas en fila"
    }
   ]
  },
  {
   "title": "🧠[Context Switches]",
   "type": "timeseries",
   "description": "Esto mide cuántas veces por segundo el procesador deja de hacer una tarea para atender otra. Un número base alto es normal en servidores, pero picos bruscos indican que hay demasiados programas peleando por el procesador.",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "instance:context_switches:rate5m{datos=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servicios Activos / Detenidos",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 10 },
   "targets": [
    {
     "expr": "windows_service_state{datos=\"$instance\", state=\"stopped\"} \r\nor \r\nnode_systemd_unit_state{datos=\"$instance\", state!=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frecuencia del CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:cpu_frequency:hertz{datos=\"$instance\"}",
     "legendFormat": "Porcentaje de uso"
    }
   ]
  },
  {
   "title": "User / Kernel",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:cpu_user:percent{datos=~\"$instance\"}",
     "legendFormat": "Usuario (Apps)"
    },
    {
     "expr": "instance:cpu_kernel:percent{datos=~\"$instance\"}",
     "legendFormat": "Sistema (Kernel)"
    }
   ]
  },
  {
   "title": "Peticiones al Sistema (System Calls)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "instance:syscalls:rate5m{datos=~\"$instance\"}",
     "legendFormat": "Llamadas al OS / sec"
    }
   ]
  },
  {
   "title": "Fuga de Hilos (Thread Count)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "instance:threads:count{datos=~\"$instance\"}",
     "legendFormat": "Hilos activos"
    }
   ]
  },
  {
   "title": "Carga por Núcleo",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:cpu_core_load:percent{datos=~\"$instance\"}",
     "legendFormat": "CPU {{core}}"
    }
   ]
  },
  { "title": "Área de memoria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "RAM Disponible",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "instance:memory_available:bytes{datos=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:ram_usage:percent{datos=~\"$instance\"}",
     "legendFormat": "% Ram en uso"
    }
   ]
  },
  {
   "title": "Errores de Página (Page Faults)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "instance:memory_page_faults:rate5m{datos=~\"$instance\"}",
     "legendFormat": "% Errores"
    }
   ]
  },
  {
   "title": "Fugas de memoria",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "instance:memory_leak_indicator:bytes{datos=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso Disco Duro ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:disk_root_usage:percent{datos=\"$instance\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "IOPS (Disco C:)",
   "type": "timeseries",
   "description": "Mide la cantidad de tareas de lectura y escritura que el disco duro procesa cada segundo. Sirve para saber si el disco está trabajando al límite de su capacidad física (sobrecarga) o si está inactivo. Si este gráfico muestra un pico alto y el gráfico de \"Latencia\" también sube, significa que el disco está saturado de trabajo.",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "instance:disk_reads:rate5m{datos=~\"$instance\"}",
     "legendFormat": "Lecturas/seg"
    },
    {
     "expr": "instance:disk_writes:rate5m{datos=~\"$instance\"}",
     "legendFormat": "Escrituras/seg"
    }
   ]
  },
  {
   "title": "💽[Latencia del Disco]",
   "type": "timeseries",
   "description": "Aquí se puede ver tanto la latencia de lectura como la de escritura en el mismo gráfico. Esto te dirá si un disco se demora mucho en responder.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "instance:disk_read_latency:rate5m{datos=~\"$instance\"}",
     "legendFormat": "Lectura"
    },
    {
     "expr": "instance:disk_write_latency:rate5m{datos=~\"$instance\"}",
     "legendFormat": "Escritura"
    }
   ]
  },
  { "title": "Área de red", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "🌐[Tráfico de red]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:network_receive_bps:rate5m{datos=~\"$instance\"})",
     "legendFormat": "📈Subida"
    },
    {
     "expr": "sum(instance:network_transmit_bps:rate5m{datos=~\"$instance\"})",
     "legendFormat": "📉Bajada"
    }
   ]
  },
  {
   "title": "📦[Perdida de paquetes]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( 1 - avg_over_time(probe_success{servidor=\"$instance\"}[5m])) * 100",
     "legendFormat": "Paquetes Perdidos"
    }
   ]
  },
  {
   "title": "🚦[Network Output Queue]",
   "type": "timeseries",
   "description": "Indica si la tarjeta de red está saturada. Si este número es mayor a 0, el servidor está intentando enviar datos más rápido de lo que el cable físico soporta.",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "instance:network_output_queue:length{datos=~\"$instance\"}",
     "legendFormat": "Paquetes en cola"
    }
   ]
  },
  {
   "title": "Latencia Actual (Ping ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(probe_icmp_duration_seconds{servidor=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ancho de Banda Actual",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(instance:network_receive_bps:rate5m{datos=~\"$instance\"}) + sum(instance:network_transmit_bps:rate5m{datos=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel de Tráfico Entrante/Saliente (Throughput)",
   "type": "timeseries",
   "description": "Vista histórica del ancho de banda que separa claramente el tráfico que entra (RX) del que sale (TX) usando un formato de gráfico espejado (positivo/negativo).",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(instance:network_receive_bps:rate5m{datos=~\"$instance\"})",
     "legendFormat": "Total RX"
    },
    {
     "expr": "sum(instance:network_transmit_bps:rate5m{datos=~\"$instance\"})",
     "legendFormat": "Total TX"
    }
   ]
  },
  {
   "title": "Intensidad de Tráfico",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 48 },
   "targets": [
    {
     "expr": "instance:network_receive_bps:rate5m{datos=~\"$instance\"}",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Errores y Descartes (Salud Crítica)",
   "type": "bargauge",
   "description": "Muestra los paquetes que llegaron corruptos o que la tarjeta de red tuvo que desechar por falta de recursos. Si no está en cero, podrías tener problemas de cableado, drivers o switches defectuosos.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:network_errors:rate5m{datos=~\"$instance\"}",
     "legendFormat": "Errores"
    },
    {
     "expr": "instance:network_drops:rate5m{datos=~\"$instance\"}",
     "legendFormat": "Descartes / Drops"
    }
   ]
  }
 ]
}