{
 "title": "Ping Info routers",
 "tags": [
  "Routers",
  "Main",
  "Pings"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sucursal",
    "label": "Seleccionar Sucursal",
    "query": {
     "query": "label_values(probe_success, sucursal)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Salud de las Sucursales (Todas)",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{sucursal=~\".+\"}[24h]) * 100"
    }
   ]
  },
  {
   "title": "Timeline de Disponibilidad",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 13, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{sucursal=\"${sucursal:raw}\"}",
     "legendFormat": "{{sucursal}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{sucursal=\"${sucursal:raw}\"}",
     "legendFormat": "{{sucursal}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{sucursal=\"${sucursal:raw}\"} * 1000",
     "legendFormat": "Ping (Current)"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{sucursal=\"${sucursal:raw}\"}[24h]) * 1000",
     "legendFormat": "Avg. Ping (24h)"
    },
    {
     "expr": "avg_over_time(probe_success{sucursal=\"${sucursal:raw}\"}[24h]) * 100",
     "legendFormat": "Uptime (24h)"
    },
    {
     "expr": "avg_over_time(probe_success{sucursal=\"${sucursal:raw}\"}[30d]) * 100",
     "legendFormat": "Uptime (30 days)"
    }
   ]
  },
  {
   "title": "Latencia en Tiempo Real",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{sucursal=\"${sucursal:raw}\"} * 1000",
     "legendFormat": "Avg Ping {{sucursal}}"
    }
   ]
  }
 ]
}